// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using calculator___server.Models;

namespace calculator___server.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20210621234238_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("calculator___server.Models.Calculation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("firstNumber")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("result")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("secondNumber")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("stringOperation")
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("id");

                    b.ToTable("calculations");
                });
#pragma warning restore 612, 618
        }
    }
}
